name: Test

on: [push, pull_request]

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-18.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
